language: node_js
node_js:
  - "7"

services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - npm run seed-travis
  - npm run test-travis
cache:
  directories:
    - "node_modules"
addons:
  postgresql: "9.6"