language: node_js
node_js:
  - "iojs"
  - "7"

services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
cache:
  directories:
    - "node_modules"
addons:
  postgresql: "9.6"